### ISSUE TITLE
Constant "is available for download".

### ISSUE THREAD

**Issue by roboserg** [supertriodo/Arena-Tracker#113]
I always had this bug, just never bother to report. I never could update the program from within itself, where it auto downloads the new version. It never worked. Once again, while updating to 7.05, it downloads the data, relaunches and says 7.05 is again, "available for download". I always have to download the full standalone release.

I am on Win10 ENg 64 bit, latest win updates, arena tracker version - all versions.

https://puu.sh/ECeYS/8b52735f2f.png

**Comment by supertriodo** [comment]
Hi, this seems to be a problem in your win 10, no idea why your system doesn't correctly remove the old binary to be replaced by the new one.

One thing you can try is to manually delete the binary just before hitting the "update" button.

I'll keep this issue report open in case it happens to more people or in case anyone can help you with a custom solution.

Thanks for your feedback though, and sorry for not being of much help in this case.

**Comment by keldian** [comment]
The issue seems pretty obvious: the program cannot delete itself while it's running, just as the user cannot. That's why most programs call upon an external binary or script to update.

**Comment by roboserg** [comment]
@supertriodo I cant delete the .exe while the program is running, windows says "the action cant be completed because the file is open in ArenaTracker.exe". I guess everyone with Windows has this issue but people don't bother and just download the new version every time, which is annoying, since the auto-uptade feature is already implemented but not quite working

@keldian Sounds logical, but why then would they release a windows version like that? With a broken auto-update feature

**Comment by supertriodo** [comment]
I'll work on a fix for this. Thx for your feefback.

**Comment by supertriodo** [comment]
Hi guys.

This bug should be fixed with these changes in the code:
https://github.com/supertriodo/Arena-Tracker/commit/2391b090dd8a4ece16d1abe9af75012e0ec84e10
https://github.com/supertriodo/Arena-Tracker/commit/3106509d44d25fb5bdf761111f80604765de73d0

I have already tested it in a Win10 installation. If you want to test it I have [prepared a exe](https://github.com/supertriodo/Arena-Tracker/releases/download/v7.1/Arena.Tracker.UPDATER.TEST.Windows.zip) that force an update on start. It will download the latest version, restart into it and show the message "v7.1 ready to use" if everything went right. You can close AT and start again from the exe to make sure the update went fine.

The version you will end up with has the autoupdater patches in so you won't have problems in the future.

Thanks for your help.

**Comment by keldian** [comment]
Hello,

No success with the new exe. I'm still getting the update prompt after restarting.

**Comment by supertriodo** [comment]
try the force update version again and let it running until the message "v7.1 ready to use" is shown at the bottom, also try to disable any antivirus which might be interfering

**Comment by roboserg** [comment]
No luck for me either, it downloads a new version (but I cant see any new files in the explorer), restarts and prompts update again. Tried with and without the admin rights.

**Comment by supertriodo** [comment]
have you used the exe I linked?

**Comment by roboserg** [comment]
yes, the Arena.Tracker.UPDATER.TEST.Windows.zip

**Comment by supertriodo** [comment]
Ok, this should work. Try https://github.com/supertriodo/Arena-Tracker/releases/download/v7.1/Arena.Tracker.UPDATER.TEST.Windows.zip

Same instruction as before:
It will download the latest version, restart into it and show the message "v7.1 ready to use" if everything went right. You can close AT and start again from the exe to make sure the update went fine.

Thanks!

**Comment by keldian** [comment]
I have left it running for 4 days straight since you to told me to let it running until a message is shown. Still no message. 

Kidding. The latest one did the trick, thanks.

**Comment by roboserg** [comment]
Yep, it works, thanks! Does that mean it is fixed for all the future releases?

**Comment by supertriodo** [comment]
Yes, it's fixed.

**Comment by roboserg** [comment]
Thanks!
